/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AutocompleteIcon: typeof import('./src/components/AutocompleteIcon.vue')['default']
    DataForm: typeof import('./src/components/DataForm.vue')['default']
    DataList: typeof import('./src/components/DataList.vue')['default']
    DataTable: typeof import('./src/components/DataTable.vue')['default']
    DensityBtn: typeof import('./src/components/DataTable/DensityBtn.vue')['default']
    ExportBtn: typeof import('./src/components/DataTable/ExportBtn.vue')['default']
    FilterBtn: typeof import('./src/components/DataTable/FilterBtn.vue')['default']
    FilterConditions: typeof import('./src/components/DataTable/FilterConditions.vue')['default']
    FilterPreview: typeof import('./src/components/DataTable/FilterPreview.vue')['default']
    OptionBtn: typeof import('./src/components/DataTable/OptionBtn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextFieldColorPicker: typeof import('./src/components/TextFieldColorPicker.vue')['default']
  }
}
